try {
  console.log(a + b);
} catch (error) {
  console.log(error);
  console.log('there was an error');
  console.log('it was save in the error log');
}
console.log('the program is still running');
